---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: federation-cluster
  labels:
    slate-federation-role-version: "v1"
rules:
- apiGroups:
  - "nrp-nautilus.io"
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - ""
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: federation-cluster-global
  labels:
    slate-federation-role-version: "v1"
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - scheduling.k8s.io
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - storage.k8s.io
  resources: ["*"]
  verbs: ["*"]
